"""domain models mab

Revision ID: c77a8e237caf
Revises: a1b2c3d4e5f6
Create Date: 2026-07-05 21:43:25.351113

Nota: originalmente derivava de 0548fa41ad4c. No merge com a main, `a1b2c3d4e5f6`
(add_is_admin_to_users) passou a ocupar esse ponto, então esta revisão foi
reencadeada para logo depois dela — evita as duas cabeças que travariam o
`alembic upgrade head`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c77a8e237caf"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casos_avaliacao",
        sa.Column("case_id", sa.String(length=60), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_arm", sa.String(length=20), nullable=False),
        sa.Column("expected_reward", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("pass_fail_criteria", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("typical", "edge", "adversarial", name="tipocasoavaliacao", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_casos_avaliacao")),
    )
    op.create_table(
        "clientes",
        sa.Column("cod_cliente", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("idade", sa.Integer(), nullable=False),
        sa.Column("tempo_relacionamento_meses", sa.Integer(), nullable=False),
        sa.Column("ind_ativo", sa.Boolean(), nullable=False),
        sa.Column("segmento", sa.String(length=40), nullable=True),
        sa.Column("estado", sa.String(length=2), nullable=True),
        sa.Column("sexo", sa.String(length=1), nullable=True),
        sa.Column("renda_estimada_anual_brl", sa.Float(), nullable=True),
        sa.Column("segmentos_sinteticos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evento_viagem_sintetico", sa.Boolean(), nullable=False),
        sa.Column(
            "origem",
            sa.Enum("seed", "demo", name="origemcliente", native_enum=False),
            nullable=False,
        ),
        sa.Column("possui_poupanca", sa.Boolean(), nullable=False),
        sa.Column("possui_conta_corrente", sa.Boolean(), nullable=False),
        sa.Column("possui_conta_corrente_plus", sa.Boolean(), nullable=False),
        sa.Column("possui_conta_premium", sa.Boolean(), nullable=False),
        sa.Column("possui_conta_salario", sa.Boolean(), nullable=False),
        sa.Column("possui_conta_junior", sa.Boolean(), nullable=False),
        sa.Column("possui_conta_universitaria", sa.Boolean(), nullable=False),
        sa.Column("possui_conta_digital", sa.Boolean(), nullable=False),
        sa.Column("possui_conta_investimento", sa.Boolean(), nullable=False),
        sa.Column("possui_cdb_curto_prazo", sa.Boolean(), nullable=False),
        sa.Column("possui_cdb_medio_prazo", sa.Boolean(), nullable=False),
        sa.Column("possui_cdb_longo_prazo", sa.Boolean(), nullable=False),
        sa.Column("possui_fundo_investimento", sa.Boolean(), nullable=False),
        sa.Column("possui_titulos_investimento", sa.Boolean(), nullable=False),
        sa.Column("possui_previdencia_privada", sa.Boolean(), nullable=False),
        sa.Column("possui_financiamento_imovel", sa.Boolean(), nullable=False),
        sa.Column("possui_financiamento_veiculo", sa.Boolean(), nullable=False),
        sa.Column("possui_emprestimo_pessoal", sa.Boolean(), nullable=False),
        sa.Column("possui_cartao_credito", sa.Boolean(), nullable=False),
        sa.Column("possui_aval_garantia", sa.Boolean(), nullable=False),
        sa.Column("possui_pagamento_tributos", sa.Boolean(), nullable=False),
        sa.Column("possui_folha_pagamento", sa.Boolean(), nullable=False),
        sa.Column("possui_beneficio_previdencia", sa.Boolean(), nullable=False),
        sa.Column("possui_debito_automatico", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("cod_cliente", name=op.f("pk_clientes")),
    )
    op.create_table(
        "experimentos",
        sa.Column("experiment_id", sa.String(length=60), nullable=False),
        sa.Column("policy_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("running", "done", name="statusexperimento", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("experiment_id", name=op.f("pk_experimentos")),
    )
    op.create_table(
        "ofertas",
        sa.Column("arm_id", sa.String(length=20), nullable=False),
        sa.Column("product_name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("credito", "investimento", "seguro", name="categoriaoferta", native_enum=False),
            nullable=False,
        ),
        sa.Column("expected_revenue_brl", sa.Float(), nullable=False),
        sa.Column("context_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("eligible_segment", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ucb_exploration_factor", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("arm_id", name=op.f("pk_ofertas")),
    )
    op.create_table(
        "politicas",
        sa.Column("policy_id", sa.String(length=60), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column(
            "algorithm",
            sa.Enum(
                "baseline", "thompson", "ucb", "linucb", name="algoritmopolitica", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("hyperparams", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("shadow", "active", "retired", name="statuspolitica", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("policy_id", name=op.f("pk_politicas")),
    )
    op.create_table(
        "segmentos",
        sa.Column("segment_id", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("segment_id", name=op.f("pk_segmentos")),
    )
    op.create_table(
        "ciclos_retreino",
        sa.Column("run_id", sa.String(length=80), nullable=False),
        sa.Column("policy_id", sa.String(length=60), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "approved",
                "promoted",
                "rolled_back",
                name="statuscicloretreino",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["politicas.policy_id"],
            name=op.f("fk_ciclos_retreino_policy_id_politicas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_ciclos_retreino")),
    )
    op.create_index(
        op.f("ix_ciclos_retreino_policy_id"), "ciclos_retreino", ["policy_id"], unique=False
    )
    op.create_table(
        "decisoes",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("cod_cliente", sa.BigInteger(), nullable=True),
        sa.Column("policy_version", sa.String(length=60), nullable=False),
        sa.Column("chosen_arm_id", sa.String(length=20), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("app", "push", "email", "sms", name="canal", native_enum=False),
            nullable=False,
        ),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chosen_arm_id"],
            ["ofertas.arm_id"],
            name=op.f("fk_decisoes_chosen_arm_id_ofertas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cod_cliente"],
            ["clientes.cod_cliente"],
            name=op.f("fk_decisoes_cod_cliente_clientes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["policy_version"],
            ["politicas.policy_id"],
            name=op.f("fk_decisoes_policy_version_politicas"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_decisoes")),
    )
    op.create_table(
        "estados_braco",
        sa.Column("policy_id", sa.String(length=60), nullable=False),
        sa.Column("arm_id", sa.String(length=20), nullable=False),
        sa.Column("alpha", sa.Float(), nullable=False),
        sa.Column("beta", sa.Float(), nullable=False),
        sa.Column("n_pulls", sa.Integer(), nullable=False),
        sa.Column("sum_reward", sa.Float(), nullable=False),
        sa.Column("A", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("b", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["arm_id"],
            ["ofertas.arm_id"],
            name=op.f("fk_estados_braco_arm_id_ofertas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["politicas.policy_id"],
            name=op.f("fk_estados_braco_policy_id_politicas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("policy_id", "arm_id", name=op.f("pk_estados_braco")),
    )
    op.create_table(
        "metricas_monitoramento",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.String(length=60), nullable=False),
        sa.Column(
            "metric",
            sa.Enum(
                "regret", "conversion", "reward", "psi_drift", name="tipometrica", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("alert", sa.Boolean(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["politicas.policy_id"],
            name=op.f("fk_metricas_monitoramento_policy_id_politicas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_metricas_monitoramento")),
    )
    op.create_index(
        op.f("ix_metricas_monitoramento_policy_id"),
        "metricas_monitoramento",
        ["policy_id"],
        unique=False,
    )
    op.create_table(
        "regras_adequacao",
        sa.Column("rule_id", sa.String(length=60), nullable=False),
        sa.Column("arm_id", sa.String(length=20), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "action",
            sa.Enum("block", "require_human", name="acaoadequacao", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["arm_id"],
            ["ofertas.arm_id"],
            name=op.f("fk_regras_adequacao_arm_id_ofertas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("rule_id", name=op.f("pk_regras_adequacao")),
    )
    op.create_index(
        op.f("ix_regras_adequacao_arm_id"), "regras_adequacao", ["arm_id"], unique=False
    )
    op.create_table(
        "aprovacoes_humanas",
        sa.Column("gate_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("approve", "reject", name="decisaoaprovacao", native_enum=False),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ciclos_retreino.run_id"],
            name=op.f("fk_aprovacoes_humanas_run_id_ciclos_retreino"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_aprovacoes_humanas_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("gate_id", name=op.f("pk_aprovacoes_humanas")),
    )
    op.create_index(
        op.f("ix_aprovacoes_humanas_run_id"), "aprovacoes_humanas", ["run_id"], unique=False
    )
    op.create_table(
        "eventos_impressao",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("impression", "click", name="tipoevento", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisoes.decision_id"],
            name=op.f("fk_eventos_impressao_decision_id_decisoes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_eventos_impressao")),
    )
    op.create_index(
        op.f("ix_eventos_impressao_decision_id"), "eventos_impressao", ["decision_id"], unique=False
    )
    op.create_table(
        "recompensas",
        sa.Column("reward_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "observed", name="statusrecompensa", native_enum=False),
            nullable=False,
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisoes.decision_id"],
            name=op.f("fk_recompensas_decision_id_decisoes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("reward_id", name=op.f("pk_recompensas")),
    )
    op.create_index(
        op.f("ix_recompensas_decision_id"), "recompensas", ["decision_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "tipo",
            sa.Enum("operador", "demo", name="tipousuario", native_enum=False),
            server_default="operador",
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("cod_cliente", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("saldo_ficticio", sa.Float(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_cod_cliente_clientes"),
        "users",
        "clientes",
        ["cod_cliente"],
        ["cod_cliente"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_cod_cliente_clientes"), "users", type_="foreignkey")
    op.drop_column("users", "saldo_ficticio")
    op.drop_column("users", "cod_cliente")
    op.drop_column("users", "tipo")
    op.drop_index(op.f("ix_recompensas_decision_id"), table_name="recompensas")
    op.drop_table("recompensas")
    op.drop_index(op.f("ix_eventos_impressao_decision_id"), table_name="eventos_impressao")
    op.drop_table("eventos_impressao")
    op.drop_index(op.f("ix_aprovacoes_humanas_run_id"), table_name="aprovacoes_humanas")
    op.drop_table("aprovacoes_humanas")
    op.drop_index(op.f("ix_regras_adequacao_arm_id"), table_name="regras_adequacao")
    op.drop_table("regras_adequacao")
    op.drop_index(op.f("ix_metricas_monitoramento_policy_id"), table_name="metricas_monitoramento")
    op.drop_table("metricas_monitoramento")
    op.drop_table("estados_braco")
    op.drop_table("decisoes")
    op.drop_index(op.f("ix_ciclos_retreino_policy_id"), table_name="ciclos_retreino")
    op.drop_table("ciclos_retreino")
    op.drop_table("segmentos")
    op.drop_table("politicas")
    op.drop_table("ofertas")
    op.drop_table("experimentos")
    op.drop_table("clientes")
    op.drop_table("casos_avaliacao")
    # ### end Alembic commands ###
